spring:
  datasource:
    url: jdbc:h2:file:~/capstone-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false  # HTTPs
        same-site: Lax

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # show_sql: true
        format_sql: true
        hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always

  cloud:
    gcp:
      project-id: spring-jpa-shop
      storage:
        bucket: spring-jpa

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6