# src/main/resources/application-cloud.yml  (배포 전용)
spring:
  cloud:
    gcp:
      storage:
        bucket: ${GCS_BUCKET}
  config:
    activate:
      on-profile: cloud
  flyway:
    enabled: true
    default-schema: public
    schemas: public
    create-schemas: true

  datasource:
    url: jdbc:postgresql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${INSTANCE_CONNECTION_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: never

gcs:
  enabled: true

