# src/main/resources/application.yml  (로컬 전용)
spring:
  application:
    name: capstone-shop

---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc.time_zone: UTC
        default_schema: public

  flyway:
    enabled: true
    default-schema: public
    schemas: public
    create-schemas: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug

gcs:
  enabled: false

file:
  upload-dir: ${java.io.tmpdir}/capstone-uploads
