-- V17__create_item_detail.sql
-- item_detail 테이블 (1:1 Item), BaseTimeEntity(created_at, updated_at) 반영

CREATE TABLE IF NOT EXISTS public.item_detail (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id      BIGINT  NOT NULL UNIQUE,
    description  TEXT,
    spec         TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FK 제약조건(중복 생성 방지)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_item_detail_item'
    ) THEN
        ALTER TABLE public.item_detail
            ADD CONSTRAINT fk_item_detail_item
            FOREIGN KEY (item_id)
            REFERENCES public.item(id)
            ON DELETE CASCADE;
    END IF;
END
$$;

-- (선택) 조회 최적화 인덱스 – UNIQUE가 이미 있지만, 이름 고정/가독성을 원하면 추가
-- CREATE INDEX IF NOT EXISTS idx_item_detail_item_id ON public.item_detail(item_id);

-- (선택) 주석
COMMENT ON TABLE  public.item_detail IS 'Item 상세(1:1)';
COMMENT ON COLUMN public.item_detail.description IS '상세 설명';
COMMENT ON COLUMN public.item_detail.spec        IS '스펙 정보';
